config/routes.rb
Rails.application.routes.draw do

  get 'info/about_us', :as=>"about_us"

  get 'info/help', :as=>"help"

  get 'recycling/index', :as => "recycling"

  get 'games/index', :as => "games"

  resources :shop, :only => [:index] do
    collection do 
      get :specials
      post :add_to_cart
    end
  end
  match 'shop/categories/:name' => "categories#show", :via => :get, :as => 'category'

  resources :administration, :as=>"admin", :only=>[:index] do
    collection do
      get :items
      get :carousel
      post :new_item
      resources :items,:only=>[:show, :update, :destroy]
    end
  end
  resources :item_types, :only=>[:update, :destroy, :create] do
    member do
      put :reset_sold
    end
  end

  resources :cart, :only=>[:index, :destroy, :update] 

  resources :users, :only=>[:index,:show,:create, :edit, :update] do
    collection do
      get :signin
    end
    member do
      get :settings
      get :history
      get :first_sign_in
      get :my_cart
    end

  end
  resources :sessions, :only=>[:create,:destroy]

  root 'home#index' 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role?(:admin)
        can :manage, :all
    else
        can :update, User, :id=>user.id
        can [:update,:destroy], Cart, :user_id=>user.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/carousel.rb
class Carousel < ActiveRecord::Base
  belongs_to :item
  attr_accessible :picture, :item, :item_id, :show
  has_attached_file :picture, :styles=>{:mobile=>"660x220"}
  validates :picture, :presence => true
  validates :item_id, :presence => true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :user, :user_id, :item_type, :item_type_id, :quantity
  validates :user_id, :presence => true
  validates :item_type_id, :presence => true
  validates :quantity, :numericality => {:greater_than => 0}
  belongs_to :user
  belongs_to :item_type
  before_destroy :return_items

  def self.add(cart_item)
  	s = self.where(:item_type_id=>cart_item[:item_type_id], :user_id=>cart_item[:user_id]).first
  	if s==nil
	  	c = self.new
	  	c.user_id = cart_item[:user_id]
	  	c.item_type_id = cart_item[:item_type_id]
	  	c.quantity = cart_item[:quantity]
	  	if c.quantity > 0
	  		if c.save
	  			i = ItemType.find(c.item_type_id)
	  			i.update_attributes(:quantity => (i.quantity - c.quantity), :reserved=>(i.reserved + c.quantity))
	  		end
	  	end
	else
		s.quantity = s.quantity + cart_item[:quantity].to_i
		if s.quantity > 0
	  		if s.save
	  			i = ItemType.find(s.item_type_id)
	  			i.update_attributes(:quantity => (i.quantity - s.quantity), :reserved=>(i.reserved + s.quantity))
	  		end
	  	end
	end
  end


  private
  	def return_items
  		@item_type = self.item_type
  		@item_type.update_attributes(:quantity => (@item_type.quantity + self.quantity), :reserved => (@item_type.reserved - self.quantity))
  	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	attr_accessible :name, :items
	has_and_belongs_to_many :items, :join_table => :categories_items
end

app/models/contactnumber.rb
class Contactnumber < ActiveRecord::Base
  belongs_to :users
  attr_accessible :contactnumber, :user_id, :user
  validates :contactnumber, phone: { possible: true, allow_blank: false, types: [:mobile] }
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :users
  attr_accessible :email, :user, :user_id
  validates :email, :presence => true
end

app/models/item.rb
class Item < ActiveRecord::Base
	attr_accessible :item_name, :categories
	
	has_many :taggings
	has_many :tags, through: :taggings
	has_many :item_types, :dependent => :destroy
	has_and_belongs_to_many :categories, :join_table=>:categories_items

	searchable do
		text :item_name
	end

	def self.tagged_with(name)
		Tag.find_by_name!(name).items
	end

	def self.tag_counts
		Tag.select("tags.*, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
	end

	def tag_list
		tags.map(&:name).join(", ")
	end

	def tag_list=(names)
		self.tags = names.split(",").map do |n|
			Tag.where(name: n.strip).first_or_create!
		end
	end
	
end

app/models/item_type.rb
class ItemType < ActiveRecord::Base
	include ActionView::Helpers::NumberHelper
	has_attached_file :picture, :styles => {:medium => "240x240"}
	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
	attr_accessible :item_id, :item, :amount, :unit, :quantity, :price, :picture, :reserved

	belongs_to :item

	def cost
		number_to_currency(self.try("price"),:unit=>"R", :precision=>2, :format=>"%u%n", :raise=>true)
	end
end

app/models/residence.rb
class Residence < ActiveRecord::Base
	attr_accessible :name
	has_many :users
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :items, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :surname, :residence_id, :contactnumber, :contactnumber_id, :studentnumber
  belongs_to :residence
  has_one :contactnumber
  has_one :email
  has_many :carts
  # validates :attribute, contactnumber: { possible: true, allow_blank: true, types: [:mobile] }
  rolify

  after_create :defaultRole 
  require 'gmail'
  def fullname
    [self.try('name'), " ", self.try("surname")].join.to_s
  end

  def total_cart_items
    return self.carts.to_a.sum {|l| l.try("quantity")} || 0
  end

  def defaultRole
    self.add_role :student
  end

  def self.authenticate(studentnumber,password)
    user = User.where(:studentnumber => studentnumber).first
    if user != nil 
      gmail = Gmail.new("#{studentnumber}@myuwc.ac.za",password)
      begin
        gmail.login
        gmail.logout
        return user
      rescue Net::IMAP::NoResponseError
        return "User Present but Invalid Credentials"
      end
    else #if user not present
      gmail = Gmail.new("#{studentnumber}@myuwc.ac.za",password)
      begin
        gmail.login
        gmail.logout
        return "Valid Credentials but not Present"
      rescue Net::IMAP::NoResponseError
        return "User Not Present and Invalid Credentials"
      end
    end      
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def signin
    if current_user
      redirect_to root_path
    end
  end

  def show
  end

  def add_to_cart
        
  end

  def first_sign_in
    @user = User.find(params[:id])

    if @user.auth != params[:auth]
      redirect_to root_path
    else
      @residences = Residence.all.map { |e| [e.name,e.id]  }
    end
  end

  def update
    u = params[:u]
    @user = User.find(params[:id])
    if u[:from] == "first_sign_in"
      @user.name = u[:name]
      @user.surname = u[:surname]
      @user.residence_id = u[:residence_id]
      if Phonelib.valid?(u[:contactnumber])
        @user.contactnumber = Contactnumber.create(:contactnumber=>u[:contactnumber])
      end  
      @user.save
    else
      
    end
    redirect_to root_path
  end

  def settings
  end

  def history
  end

  def create
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/recycling_helper.rb
module RecyclingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/first_sign_in.html.erb
<div class="container-fluid">
	<div class="row hidden-md hidden-lg">
		<div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-4">
				<%=form_for(:u, :url=>user_path(@user), :method=>:put) do |f|%>
					<%=f.hidden_field :from, :value=>"first_sign_in"%>
					<div class="well well-sm form-group">
						<h2 style="margin-top:0px;">Personal Details</h2>
						<%=f.text_field :name, :class=>"form-control", :placeholder=>"First name"%>
						<br>
						<%=f.text_field :surname, :class=>"form-control", :placeholder=>"Last name"%>
					</div>
					<div class="well well-sm form-group">
						<h2 style="margin-top:0px;">Residence</h2>
						<%=f.select(:residences_id, @residences,{}, :class=>"form-control")%>
					</div>
					<div class="well well-sm form-group">
						<h2 style="margin-top:0px;">Contact Details</h2>
						<%=f.text_field :contactnumber, :class=>"form-control", :placeholder=>"Cellphone Number"%>
					</div>
					<%=f.submit "Update", :class=>"btn btn-primary btn-block"%>
				<%end%>
				<center><%=link_to "Skip", root_path%></center>
		</div>
	</div>
	<div class="row hidden-xs hidden-sm">
		<div class="col-xs-10 col-sm-4 ">
				<%=form_for(:u, :url=>user_path(@user), :method=>:put) do |f|%>
					<%=f.hidden_field :from, :value=>"first_sign_in"%>
					<div class="well well-sm form-group">
						<h2 style="margin-top:0px;">Personal Details</h2>
						<%=f.text_field :name, :class=>"form-control", :placeholder=>"First name"%>
						<br>
						<%=f.text_field :surname, :class=>"form-control", :placeholder=>"Last name"%>
					</div>
					<div class="well well-sm form-group">
						<h2 style="margin-top:0px;">Residence</h2>
						<%=f.select(:residences_id, @residences,{}, :class=>"form-control")%>
					</div>
					<div class="well well-sm form-group">
						<h2 style="margin-top:0px;">Contact Details</h2>
						<%=f.text_field :contactnumber, :class=>"form-control", :placeholder=>"Cellphone Number"%>
					</div>
					<%=f.submit "Update", :class=>"btn btn-primary btn-block"%>
				<%end%>
				<center><%=link_to "Skip", root_path%></center>
		</div>
	</div>
</div>

app/views/users/history.html.erb
<script type="text/javascript">
	$("#<%=action_name%>").addClass("active");
	$("#show").removeClass("active");
	$("#settings").removeClass("active");
</script>

app/views/users/my_cart.html.erb
my_cart.html.erb

app/views/users/settings.html.erb
<script type="text/javascript">
	$("#<%=action_name%>").addClass("active");
	$("#show").removeClass("active");
	$("#history").removeClass("active");
</script>

app/views/users/signin.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<center>
				<%=image_tag("logo.png")%>
			</center>
		</div>
		<div class="col-xs-10 col-xs-offset-1 col-sm-4 col-sm-offset-4 col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4">
			<center><h1>Sign In</h1></center>
			<%=form_for(:user, :url=>sessions_path, :method=>:post) do |f|%>
				<div class="form-group <%=params[:errors]==nil ? '' : 'has-error'%>">
					<%=f.text_field :studentnumber, :class=>"form-control input-lg", :required=>"true", :maxlength=>"7", :autofocus=>true, :placeholder=>"Student Number"%>
				</div>
				<div class="form-group <%=params[:errors]==nil ? '' : 'has-error'%>">
					<%=f.password_field :password, :class=>"form-control input-lg", :required=>"true", :placeholder=>"Password"%>
				</div>
				<%=f.submit "Begin", :class=>"btn btn-primary btn-block"%>
			<%end%>
		</div>
	</div>
</div>