config/routes.rb
Rails.application.routes.draw do

  get 'info/about_us', :as=>"about_us"

  get 'info/help', :as=>"help"

  get 'recycling/index', :as => "recycling"

  get 'games/index', :as => "games"

  resources :shop, :only => [:index] do
    collection do 
      get :specials
      post :add_to_cart
    end
  end
  match 'shop/categories/:name' => "categories#show", :via => :get, :as => 'category'

  resources :administration, :as=>"admin", :only=>[:index] do
    collection do
      get :items
      get :carousel
      post :new_item
      resources :items,:only=>[:show, :update, :destroy]
    end
  end
  resources :item_types, :only=>[:update, :destroy, :create] do
    member do
      put :reset_sold
    end
  end

  resources :cart, :only=>[:index, :destroy, :update] 

  resources :users, :only=>[:index,:show,:create, :edit, :update] do
    collection do
      get :signin
    end
    member do
      get :settings
      get :history
      get :first_sign_in
      get :my_cart
    end

  end
  resources :sessions, :only=>[:create,:destroy]

  root 'home#index' 

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role?(:admin)
        can :manage, :all
    else
        can :update, User, :id=>user.id
        can [:update,:destroy], Cart, :user_id=>user.id
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/carousel.rb
class Carousel < ActiveRecord::Base
  belongs_to :item
  attr_accessible :picture, :item, :item_id, :show
  has_attached_file :picture, :styles=>{:mobile=>"660x220"}
  validates :picture, :presence => true
  validates :item_id, :presence => true
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :user, :user_id, :item_type, :item_type_id, :quantity
  validates :user_id, :presence => true
  validates :item_type_id, :presence => true
  validates :quantity, :numericality => {:greater_than => 0}
  belongs_to :user
  belongs_to :item_type
  before_destroy :return_items

  def self.add(cart_item)
  	s = self.where(:item_type_id=>cart_item[:item_type_id], :user_id=>cart_item[:user_id]).first
  	if s==nil
	  	c = self.new
	  	c.user_id = cart_item[:user_id]
	  	c.item_type_id = cart_item[:item_type_id]
	  	c.quantity = cart_item[:quantity]
	  	if c.quantity > 0
	  		if c.save
	  			i = ItemType.find(c.item_type_id)
	  			i.update_attributes(:quantity => (i.quantity - c.quantity), :reserved=>(i.reserved + c.quantity))
	  		end
	  	end
	else
		s.quantity = s.quantity + cart_item[:quantity].to_i
		if s.quantity > 0
	  		if s.save
	  			i = ItemType.find(s.item_type_id)
	  			i.update_attributes(:quantity => (i.quantity - s.quantity), :reserved=>(i.reserved + s.quantity))
	  		end
	  	end
	end
  end


  private
  	def return_items
  		@item_type = self.item_type
  		@item_type.update_attributes(:quantity => (@item_type.quantity + self.quantity), :reserved => (@item_type.reserved - self.quantity))
  	end
end

app/models/category.rb
class Category < ActiveRecord::Base
	attr_accessible :name, :items
	has_and_belongs_to_many :items, :join_table => :categories_items
end

app/models/contactnumber.rb
class Contactnumber < ActiveRecord::Base
  belongs_to :users
  attr_accessible :contactnumber, :user_id, :user
  validates :contactnumber, phone: { possible: true, allow_blank: false, types: [:mobile] }
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :users
  attr_accessible :email, :user, :user_id
  validates :email, :presence => true
end

app/models/item.rb
class Item < ActiveRecord::Base
	attr_accessible :item_name, :categories
	
	has_many :taggings
	has_many :tags, through: :taggings
	has_many :item_types, :dependent => :destroy
	has_and_belongs_to_many :categories, :join_table=>:categories_items

	searchable do
		text :item_name
	end

	def self.tagged_with(name)
		Tag.find_by_name!(name).items
	end

	def self.tag_counts
		Tag.select("tags.*, count(taggings.tag_id) as count").joins(:taggings).group("taggings.tag_id")
	end

	def tag_list
		tags.map(&:name).join(", ")
	end

	def tag_list=(names)
		self.tags = names.split(",").map do |n|
			Tag.where(name: n.strip).first_or_create!
		end
	end
	
end

app/models/item_type.rb
class ItemType < ActiveRecord::Base
	include ActionView::Helpers::NumberHelper
	has_attached_file :picture, :styles => {:medium => "240x240"}
	validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
	attr_accessible :item_id, :item, :amount, :unit, :quantity, :price, :picture, :reserved

	belongs_to :item

	def cost
		number_to_currency(self.try("price"),:unit=>"R", :precision=>2, :format=>"%u%n", :raise=>true)
	end
end

app/models/residence.rb
class Residence < ActiveRecord::Base
	attr_accessible :name
	has_many :users
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :items, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :item
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :surname, :residence_id, :contactnumber, :contactnumber_id, :studentnumber
  belongs_to :residence
  has_one :contactnumber
  has_one :email
  has_many :carts
  # validates :attribute, contactnumber: { possible: true, allow_blank: true, types: [:mobile] }
  rolify

  after_create :defaultRole 
  require 'gmail'
  def fullname
    [self.try('name'), " ", self.try("surname")].join.to_s
  end

  def total_cart_items
    return self.carts.to_a.sum {|l| l.try("quantity")} || 0
  end

  def defaultRole
    self.add_role :student
  end

  def self.authenticate(studentnumber,password)
    user = User.where(:studentnumber => studentnumber).first
    if user != nil 
      gmail = Gmail.new("#{studentnumber}@myuwc.ac.za",password)
      begin
        gmail.login
        gmail.logout
        return user
      rescue Net::IMAP::NoResponseError
        return "User Present but Invalid Credentials"
      end
    else #if user not present
      gmail = Gmail.new("#{studentnumber}@myuwc.ac.za",password)
      begin
        gmail.login
        gmail.logout
        return "Valid Credentials but not Present"
      rescue Net::IMAP::NoResponseError
        return "User Not Present and Invalid Credentials"
      end
    end      
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom:0;">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to raw("<i class='fa fa-shopping-cart'></i> My Cart (#{current_user.total_cart_items})"), cart_index_path, :class=>"btn btn-default hidden-sm hidden-md hidden-lg", :style=>"float:right; margin-top:8px; margin-right:8px;"%>
			<%= link_to image_tag("logo.png", :height=>"50"), root_path, :class=>"navbar-brand", :style=>"padding:0;"%>
		</div>
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">	
			<ul class="nav navbar-nav hidden-md hidden-lg">
				<li class="active"><%= link_to raw("<i class='fa fa-home'></i> Home"), root_path%></li>
				<li><%= link_to raw("<i class='fa fa-money'></i> Shop"), shop_index_path%></li>
				<li><%= link_to raw("<i class='fa fa-tags'></i> Specials"), specials_shop_index_path%></li>
				<li><%= link_to raw("<i class='fa fa-gamepad'></i> Quizzes and Games"), games_path%></li>
				<li><%= link_to raw("<i class='fa fa-recycle'></i> Recycling"), recycling_path%></li>
				<li class="divider"></li>
				<li><%= link_to raw("<i class='fa fa-users'></i> About Us"), about_us_path%></li>
				<li><%= link_to raw("<i class='fa fa-question'></i> Help"), help_path%></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li class="divider"></li>
				<%if current_user.has_role? :admin%>
					<li><%= link_to raw("<i class='fa fa-dashboard'></i> Admin Dashboard"), admin_index_path, :class=>"visible-md visible-lg"%></li>
				<%end%>
				<%= link_to raw("<i class='fa fa-shopping-cart'></i> My Cart (#{current_user.total_cart_items})"), cart_index_path, :class=>"btn btn-default hidden-xs", :style=>"float:left;margin-top:8px;"%>
				<li class="dropdown visible-md visible-lg"><a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class='fa fa-user'></i> <%=current_user.fullname%> <span class="caret"></span></a>
					<ul class="dropdown-menu" role="menu">	
			            <li><%= link_to "Profile", user_path(current_user)%></li>
			            <li><%= link_to "Account Settings", settings_user_path(current_user)%></li>
			            <li><%= link_to "Transaction History", history_user_path(current_user)%></li>
					</ul>
				</li>
				<li class="visible-xs visible-sm"><%= link_to raw("<i class='fa fa-user'></i> #{current_user.fullname}"), user_path(current_user)%></li>
				<li><%= link_to raw("<i class='fa fa-sign-out'></i> Sign Out"), session_path(current_user), :method=>:delete%></li>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/_sidebar.html.erb
<nav class="navbar-default col-md-2 col-lg-2 visible-md visible-lg sidebar">
	<ul class="nav nav-sidebar ">
		<%if !["administration", "items"].include?(controller_name)%>
			<!-- Normal menu -->
			<li class="active"><%= link_to raw("<i class='fa fa-home'></i> Home"), root_path%></li>
			<li><%= link_to raw("<i class='fa fa-money'></i> Shop"), shop_index_path%></li>
			<li><%= link_to raw("<i class='fa fa-tags'></i> Specials"), specials_shop_index_path%></li>
			<li><%= link_to raw("<i class='fa fa-gamepad'></i> Quizzes and Games"), games_path%></li>
			<li><%= link_to raw("<i class='fa fa-recycle'></i> Recycling"), recycling_path%></li>
			<li class="divider"></li>
			<li><%= link_to raw("<i class='fa fa-users'></i> About Us"), about_us_path%></li>
			<li><%= link_to raw("<i class='fa fa-question'></i> Help"), help_path%></li>
		<%else%>
			<!-- Menu for Admin console -->
			<li><%= link_to "Carousel", carousel_admin_index_path%></li>
			<li><%= link_to "Items", items_admin_index_path%></li>
			<li><%= link_to "Orders", "#"%></li>
		<%end%>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Enactus</title>
  <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1,user-scalable=no,minimal-ui">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag :modernizr %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container-fluid" style="padding-left:0;padding-right:0;">
	<%=render "layouts/navigation" unless (current_user == nil || action_name =="first_sign_in")%>
	<%=render "layouts/sidebar" unless (current_user == nil || action_name =="first_sign_in")%>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9 col-md-offset-2 col-lg-offset-2 content">
      <%if (controller_name=="users" && action_name!="signin")%>
        <center>
          <ul class="nav nav-pills user-show-nav hidden-md hidden-lg" id="user-nav">
            <li class="active" id="show"><%=link_to "Profile", user_path(current_user)%></li>
            <li id="settings"><%= link_to "Account Settings", settings_user_path(current_user)%></li>
            <li id="history"><%= link_to "Transaction History", history_user_path(current_user)%></li>
          </ul>
        </center>
      <%end%>
      <br>
      <%=yield%>
    </div>
  </div>
  </div>
	<nav class="navbar navbar-default navbar-fixed-bottom visible-md visible-lg" role="footer">
  		<div class="container-fluid">
    		<ul class="nav navbar-nav">
    			<li><%=link_to raw("Unilever"), "http://www.unilever.co.za"%></li>
    			<li class="divider"></li>
    			<li><%=link_to "Western Cape CoLab", "http://2014.colabwc.co.za"%></li>
    		</ul>
  		</div>
  	</nav>
</body>

</html>